version: '3.1'

services:
  nginx:
    image: stolemyusername/engauge-nginx:latest
    depends_on:
      - 'app'
      - 'landing'
    networks:
      - traefik-net
      - engauge
  app:
    image: stolemyusername/engauge-app:latest
    env_file: .env
    depends_on:
      - 'database'
    networks:
      - engauge
  landing:
    image: stolemyusername/engauge-landing:latest
    networks:
      - engauge
  screenshot:
    image: stolemyusername/engauge-screenshot:latest
    env_file: .env
    networks:
      - engauge
      - minio-distributed
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  database:
    image: postgres:9.6
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - engauge-db:/var/lib/postgresql/data
    networks:
      - engauge
volumes:
  engauge-db:
networks:
  engauge:
    external: true
  traefik-net:
    external: true
  minio-distributed:
    external: true