version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  web: # name of the first service
    build: . # specify the directory of the Dockerfile
    ports:
      - "3000:3000" # specify port forewarding
    links:
      - database
  database: # name of the third service
    image: postgres:latest # specify image to build container from
    ports:
      - "5432:5432" # specify port forewarding
    env_file: docker-compose.env
