<<<<<<< HEAD
version: '3' # specify docker-compose version
||||||| parent of aec4375... Remove dependeancy on minio
version: '3'
=======
version: '3.1'
>>>>>>> aec4375... Remove dependeancy on minio

# Define the services/containers to be run
services:
  nginx:
<<<<<<< HEAD
    image: stolemyusername/nginx:latest # specify image to build container from
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    # volumes:
      # Generate the keys locally with:
      # openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout privkey.pem -out fullchain.pem
      # - ~/.localhost/:/etc/letsencrypt/live/ebcert/
    links:
      - app
      - landing
      - screenshot
||||||| parent of 6b93fae... Expose ports
    image: stolemyusername/engauge-nginx:arm
=======
    image: stolemyusername/engauge-nginx:arm
<<<<<<< HEAD
    expose:
      - 80
>>>>>>> 6b93fae... Expose ports
||||||| parent of c299c3b... asd
    expose:
      - 80
=======
>>>>>>> c299c3b... asd
    depends_on:
      - 'app'
      - 'landing'
<<<<<<< HEAD
<<<<<<< HEAD
  app: # name of the first service
    image: stolemyusername/engauge:latest # specify image to build container from
||||||| parent of b3eff29... asda
    environment:
      VIRTUAL_HOST: engauge.xyz,www.engauge.xyz,app.engauge.xyz
      LETSENCRYPT_HOST: engauge.xyz,www.engauge.xyz,app.engauge.xyz
      LETSENCRYPT_EMAIL: guythomas721@gmail.com
    deploy:
      placement:
        constraints:
         - node.labels.arch == arm
  app:
    image: stolemyusername/engauge-app:arm
=======
    environment:
      VIRTUAL_HOST: engauge.xyz,www.engauge.xyz,app.engauge.xyz
      LETSENCRYPT_HOST: engauge.xyz,www.engauge.xyz,app.engauge.xyz
      LETSENCRYPT_EMAIL: guythomas721@gmail.com
||||||| parent of 698e153... Change to new network name
    environment:
      VIRTUAL_HOST: engauge.xyz,www.engauge.xyz,app.engauge.xyz
      LETSENCRYPT_HOST: engauge.xyz,www.engauge.xyz,app.engauge.xyz
      LETSENCRYPT_EMAIL: guythomas721@gmail.com
=======
>>>>>>> 698e153... Change to new network name
    deploy:
      labels:
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:www.engauge.xyz,engauge.xyz,app.engauge.xyz"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.port=80"
        - "traefik.enable=true"
      placement:
        constraints:
         - node.labels.arch == arm
    networks:
      - traefik-net
      - engauge-net
  app:
    image: stolemyusername/engauge-app:arm
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> b3eff29... asda
    ports:
      - "3000:3000" # specify port forewarding
    links:
      - database
||||||| parent of 6100c94... Remove explicit ports
    ports:
      - "3000:3000"
=======
    # ports:
    #   - "3000:3000"
>>>>>>> 6100c94... Remove explicit ports
||||||| parent of f8f99f3... Change so that port references refer to the internal port
    # ports:
    #   - "3000:3000"
=======
>>>>>>> f8f99f3... Change so that port references refer to the internal port
||||||| parent of 6b93fae... Expose ports
=======
    expose:
      - 3000
>>>>>>> 6b93fae... Expose ports
||||||| parent of c299c3b... asd
    expose:
      - 3000
=======
>>>>>>> c299c3b... asd
||||||| parent of 8c1961a... Add port exposing for testing purposes
=======
    ports:
      - "3000:3000"
>>>>>>> 8c1961a... Add port exposing for testing purposes
||||||| parent of 5d1b526... asd
    ports:
      - "3000:3000"
=======
>>>>>>> 5d1b526... asd
    env_file: .env
    depends_on:
      - 'database'
<<<<<<< HEAD
<<<<<<< HEAD
||||||| parent of b3eff29... asda
    deploy:
      placement:
        constraints:
         - node.labels.arch == arm
=======
    # deploy:
    #   placement:
    #     constraints:
    #      - node.labels.arch == arm
>>>>>>> b3eff29... asda
||||||| parent of 3773c27... adas
    # deploy:
    #   placement:
    #     constraints:
    #      - node.labels.arch == arm
=======
    deploy:
      placement:
        constraints:
<<<<<<< HEAD
<<<<<<< HEAD
         - node.hostname = node2
<<<<<<< HEAD
>>>>>>> 3773c27... adas
||||||| parent of 1bd4316... ads
=======
||||||| parent of 8d805e2... asd
         - node.hostname = node2
=======
         - node.hostname == node2
>>>>>>> 8d805e2... asd
||||||| parent of 65531f1... Make constraints more generic
         - node.hostname == node2
=======
         - node.labels.arch == arm
>>>>>>> 65531f1... Make constraints more generic
    networks:
<<<<<<< HEAD
      - engauge
<<<<<<< HEAD
      - minio-distributed
>>>>>>> 1bd4316... ads
||||||| parent of aec4375... Remove dependeancy on minio
      - minio-distributed
=======
>>>>>>> aec4375... Remove dependeancy on minio
||||||| parent of e5ff548... as
      - engauge
=======
      - engauge-net
>>>>>>> e5ff548... as
  landing:
<<<<<<< HEAD
    image: stolemyusername/engauge-landing:latest # specify image to build container from
    ports:
      - "3001:3001"
<<<<<<< HEAD
<<<<<<< HEAD
    links:
      - app
      - screenshot
  database: # name of the third service
    image: postgres:9.6 # specify image to build container from
||||||| parent of b3eff29... asda
    deploy:
      placement:
        constraints:
         - node.labels.arch == arm
  screenshot:
    image: stolemyusername/engauge-screenshot:latest
=======
    # deploy:
    #   placement:
    #     constraints:
    #      - node.labels.arch == arm
||||||| parent of 3773c27... adas
    # deploy:
    #   placement:
    #     constraints:
    #      - node.labels.arch == arm
=======
||||||| parent of 6100c94... Remove explicit ports
    image: stolemyusername/engauge-landing:arm
<<<<<<< HEAD
    ports:
      - "3001:3001"
=======
    image: stolemyusername/engauge-landing:arm
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    # ports:
    #   - "3001:3001"
>>>>>>> 6100c94... Remove explicit ports
||||||| parent of f8f99f3... Change so that port references refer to the internal port
    # ports:
    #   - "3001:3001"
=======
>>>>>>> f8f99f3... Change so that port references refer to the internal port
||||||| parent of 6b93fae... Expose ports
=======
    expose:
      - 3001
>>>>>>> 6b93fae... Expose ports
||||||| parent of c299c3b... asd
    expose:
      - 3001
=======
>>>>>>> c299c3b... asd
||||||| parent of 8c1961a... Add port exposing for testing purposes
=======
    ports:
      - "3001:3001"
>>>>>>> 8c1961a... Add port exposing for testing purposes
||||||| parent of 5d1b526... asd
    ports:
      - "3001:3001"
=======
>>>>>>> 5d1b526... asd
    deploy:
      placement:
        constraints:
<<<<<<< HEAD
<<<<<<< HEAD
         - node.hostname = node2
<<<<<<< HEAD
>>>>>>> 3773c27... adas
||||||| parent of 698e153... Change to new network name
=======
||||||| parent of 8d805e2... asd
         - node.hostname = node2
=======
         - node.hostname == node2
>>>>>>> 8d805e2... asd
||||||| parent of 65531f1... Make constraints more generic
         - node.hostname == node2
=======
         - node.labels.arch == arm
>>>>>>> 65531f1... Make constraints more generic
    networks:
<<<<<<< HEAD
      - engauge
<<<<<<< HEAD
      - minio-distributed
>>>>>>> 698e153... Change to new network name
||||||| parent of d785e83... Add testing configurations
      - minio-distributed
=======
>>>>>>> d785e83... Add testing configurations
||||||| parent of e5ff548... as
      - engauge
=======
      - engauge-net
>>>>>>> e5ff548... as
  screenshot:
    image: stolemyusername/engauge-screenshot:latest
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> b3eff29... asda
    ports:
      - "5432:5432" # specify port forewarding
||||||| parent of 6100c94... Remove explicit ports
    ports:
      - "3002:3002"
=======
    # ports:
    #   - "3002:3002"
>>>>>>> 6100c94... Remove explicit ports
||||||| parent of f8f99f3... Change so that port references refer to the internal port
    # ports:
    #   - "3002:3002"
=======
>>>>>>> f8f99f3... Change so that port references refer to the internal port
||||||| parent of 6b93fae... Expose ports
=======
    expose:
      - 3002
>>>>>>> 6b93fae... Expose ports
||||||| parent of c299c3b... asd
    expose:
      - 3002
=======
>>>>>>> c299c3b... asd
||||||| parent of 8c1961a... Add port exposing for testing purposes
=======
    ports:
      - "3002:3002"
>>>>>>> 8c1961a... Add port exposing for testing purposes
||||||| parent of 5d1b526... asd
    ports:
      - "3002:3002"
=======
>>>>>>> 5d1b526... asd
    env_file: .env
<<<<<<< HEAD
<<<<<<< HEAD
    volumes:
      - enguage-db:/var/lib/postgresql/data
  screenshot: # name of the third service
    image: stolemyusername/engauge-screenshot:latest # specify image to build container from
||||||| parent of b3eff29... asda
    deploy:
      placement:
        constraints:
         - node.labels.arch == x86
  database:
    image: tobi312/rpi-postgresql
=======
    # deploy:
    #   placement:
    #     constraints:
    #      - node.labels.arch == x86
||||||| parent of 3773c27... adas
    # deploy:
    #   placement:
    #     constraints:
    #      - node.labels.arch == x86
=======
    deploy:
      placement:
        constraints:
<<<<<<< HEAD
<<<<<<< HEAD
         - node.hostname = master
<<<<<<< HEAD
>>>>>>> 3773c27... adas
||||||| parent of 1bd4316... ads
=======
||||||| parent of 8d805e2... asd
         - node.hostname = master
=======
         - node.hostname == master
>>>>>>> 8d805e2... asd
||||||| parent of 65531f1... Make constraints more generic
         - node.hostname == master
=======
         - node.labels.arch == x86
>>>>>>> 65531f1... Make constraints more generic
    networks:
<<<<<<< HEAD
      - engauge
<<<<<<< HEAD
      - minio-distributed
>>>>>>> 1bd4316... ads
||||||| parent of aec4375... Remove dependeancy on minio
      - minio-distributed
=======
||||||| parent of e5ff548... as
      - engauge
=======
      - engauge-net
>>>>>>> e5ff548... as
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
>>>>>>> aec4375... Remove dependeancy on minio
  database:
<<<<<<< HEAD
    image: tobi312/rpi-postgresql
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> b3eff29... asda
    ports:
      - "3002:3002" # specify port forewarding
||||||| parent of 6100c94... Remove explicit ports
    ports:
      - "5432:5432"
=======
    # ports:
    #   - "5432:5432"
>>>>>>> 6100c94... Remove explicit ports
||||||| parent of f8f99f3... Change so that port references refer to the internal port
    # ports:
    #   - "5432:5432"
=======
>>>>>>> f8f99f3... Change so that port references refer to the internal port
||||||| parent of 6b93fae... Expose ports
=======
    expose:
      - 5432
>>>>>>> 6b93fae... Expose ports
||||||| parent of c299c3b... asd
    expose:
      - 5432
=======
>>>>>>> c299c3b... asd
||||||| parent of aec4375... Remove dependeancy on minio
    image: tobi312/rpi-postgresql
=======
    image: tobi312/rpi-postgresql:9.6
>>>>>>> aec4375... Remove dependeancy on minio
    env_file: .env
<<<<<<< HEAD
<<<<<<< HEAD
||||||| parent of b3eff29... asda
    volumes:
      - engauge-db:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
         - node.labels.arch == arm
=======
||||||| parent of 9ac8114... Change port mappings
=======
    ports:
      - "5432:5432"
>>>>>>> 9ac8114... Change port mappings
    volumes:
<<<<<<< HEAD
<<<<<<< HEAD
      - engauge-db:/var/lib/postgresql/data
<<<<<<< HEAD
    # deploy:
    #   placement:
    #     constraints:
    #      - node.labels.arch == arm
>>>>>>> b3eff29... asda
||||||| parent of 3773c27... adas
    # deploy:
    #   placement:
    #     constraints:
    #      - node.labels.arch == arm
=======
||||||| parent of e5ff548... as
      - engauge-db:/var/lib/postgresql/data
=======
      - engauge-net-db:/var/lib/postgresql/data
>>>>>>> e5ff548... as
||||||| parent of 6c5eea5... sad
      - engauge-net-db:/var/lib/postgresql/data
=======
      - engauge-db:/var/lib/postgresql/data
>>>>>>> 6c5eea5... sad
    deploy:
      placement:
        constraints:
<<<<<<< HEAD
         - node.hostname == node3
<<<<<<< HEAD
>>>>>>> 3773c27... adas
||||||| parent of 698e153... Change to new network name
=======
||||||| parent of 65531f1... Make constraints more generic
         - node.hostname == node3
=======
         - node.labels.arch == arm
>>>>>>> 65531f1... Make constraints more generic
    networks:
<<<<<<< HEAD
<<<<<<< HEAD
      - enguage
>>>>>>> 698e153... Change to new network name
||||||| parent of 7e315b2... asd
      - enguage
=======
      - engauge
>>>>>>> 7e315b2... asd
||||||| parent of e5ff548... as
      - engauge
=======
      - engauge-net
>>>>>>> e5ff548... as
volumes:
<<<<<<< HEAD
  enguage-db:
||||||| parent of 3773c27... adas
  engauge-db:
networks:
<<<<<<< HEAD
  default:
    external:
      name: nginx-proxy
=======
  engauge-db:
networks:
<<<<<<< HEAD
  minio-distributed:
    external: true
<<<<<<< HEAD
  default:
    external:
<<<<<<< HEAD
<<<<<<< HEAD
      name: minio-distributed
    external:
      name: nginx-proxy
    external:
      name: engauge
>>>>>>> 3773c27... adas
||||||| parent of 1bd4316... ads
      name: minio-distributed
    external:
      name: nginx-proxy
    external:
      name: engauge
=======
      name: enguage
>>>>>>> 1bd4316... ads
||||||| parent of b41fe0d... Fix typo
      name: enguage
=======
      name: engauge
>>>>>>> b41fe0d... Fix typo
||||||| parent of 698e153... Change to new network name
  default:
    external:
      name: engauge
=======
||||||| parent of d785e83... Add testing configurations
  minio-distributed:
    external: true
=======
>>>>>>> d785e83... Add testing configurations
  engauge:
||||||| parent of e5ff548... as
  engauge:
=======
  engauge-net:
>>>>>>> e5ff548... as
    external: true
  traefik-net:
<<<<<<< HEAD
    external: true
>>>>>>> 698e153... Change to new network name
||||||| parent of d785e83... Add testing configurations
    external: true
=======
    external: true
<<<<<<< HEAD
  minio-distributed:
    external: true
>>>>>>> d785e83... Add testing configurations
||||||| parent of aec4375... Remove dependeancy on minio
  minio-distributed:
    external: true
=======
secrets:
  AWS_ACCESS_KEY_ID:
    external: true
  AWS_SECRET_ACCESS_KEY:
    external: true
>>>>>>> aec4375... Remove dependeancy on minio
